# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXJ1wyujSPbb8TrpASa1XdVz_bWOEyQS
"""

import pandas as pd
import numpy as np

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Titanic-Dataset.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yasserh/titanic-dataset",
  file_path,
)
cleaned_df = df.copy()

for i in df.columns:
    if df[i].dtype != "int64":
        print(i)
cleaned_df.drop(["Name","Ticket"],inplace=True,axis=1)

#AGE

import seaborn as sns
import matplotlib.pyplot as plt

df["Age"].plot.box()
plt.show()

cleaned_df["Age"] = cleaned_df["Age"].fillna((df["Age"]).median())
cleaned_df["Age"] = cleaned_df["Age"].astype(int)

##CABIN
cleaned_df["CABIN_DECK"] = cleaned_df["Cabin"].str[0]
cleaned_df["CABIN_DECK"] = cleaned_df["CABIN_DECK"].fillna(cleaned_df["CABIN_DECK"].mode()[0])
cleaned_df = pd.get_dummies(cleaned_df,columns=["CABIN_DECK"],drop_first=True)
cleaned_df.drop("Cabin",axis=1,inplace=True)

#Sex
cleaned_df = pd.get_dummies(cleaned_df,columns=["Sex"],drop_first=True)

#Embarked
cleaned_df['Embarked'] = cleaned_df["Embarked"].fillna(df["Embarked"].mode()[0])
cleaned_df = pd.get_dummies(cleaned_df,columns=["Embarked"],drop_first=True)

cleaned_df.hist(figsize=(12, 8), bins=20, edgecolor="black")

plt.tight_layout()

plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(data=cleaned_df.select_dtypes(include="number"))

plt.xticks(rotation=45)

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(
    cleaned_df[["Age", "Fare", "Pclass", "SibSp", "Parch"]],
    diag_kind="hist"
)

plt.show()