# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oByU9O0GDJEz8YSabJImHOsW-KWPSwY
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import kagglehub

path = kagglehub.dataset_download("harishkumardatalab/housing-price-prediction")

print("Path to dataset files:", path)

import os
data = pd.read_csv(os.path.join(path, 'Housing.csv'))

df = data.copy()

for col in data:
  if(data[col].dtype != "int64"):
    print(col)

Y = df["price"]
X = df.drop("price", axis=1)

mapping = {"yes": 1, "no": 0}

binary_cols = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

for col in binary_cols:
    X[col] = X[col].map(mapping)

X = pd.get_dummies(X, columns=["furnishingstatus"], dtype=int)

lr = LinearRegression()
Scaler = StandardScaler()

scaled_inputs = Scaler.fit_transform(X)

X_train,X_test,Y_train,Y_test = train_test_split(scaled_inputs,Y,test_size=0.2,random_state=42)

model = lr.fit(X_train,Y_train)

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(Y_test, y_pred))

print("MSE:", mean_squared_error(Y_test, y_pred))

print("RMSE:", np.sqrt(mean_squared_error(Y_test, y_pred)))

print("R² Score:", r2_score(Y_test, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
plt.scatter(Y_test, y_pred, alpha=0.7)
plt.plot(
    [Y_test.min(), Y_test.max()],
    [Y_test.min(), Y_test.max()],
    color="red",
    linestyle="--"
)
plt.xlabel("Actual House Price")
plt.ylabel("Predicted House Price")
plt.title("Actual vs Predicted Prices")
plt.show()