# -*- coding: utf-8 -*-
"""day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lGp61TWBh4ZZ5yPgYcZv1YqVMxcXxT7
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "heart.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "johnsmith88/heart-disease-dataset",
  file_path,
)

df.head()

X = df.drop("target",axis=1)
Y = df["target"]

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train,Y_train)
predict = model_dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(Y_test, predict))

plt.figure(figsize=(18,10))

plot_tree(
    model_dt,
    feature_names=X.columns,
    class_names=["No Disease", "Disease"],
    filled=True,
    rounded=True,
    fontsize=8
)

plt.show()

print("DT Training Accuracy:", model_dt.score(X_train, Y_train))
print("DT Testing Accuracy :", model_dt.score(X_test, Y_test))

model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train,Y_train)
predict_rf = model_rf.predict(X_test)

print("Training Accuracy:", model_rf.score(X_train, Y_train))
print("Testing Accuracy :", model_rf.score(X_test, Y_test))

Importance = pd.DataFrame({
    "col":X_train.columns,
    "val":model_rf.feature_importances_
})
Importance.sort_values("val")

score = cross_val_score(model_rf,X,Y)

print("Scores:", score)
print("Average Accuracy:", score.mean())