# -*- coding: utf-8 -*-
"""day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-x-RxnMv4JZvwdueKgko-GOsGKFyJgh
"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Iris.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/iris",
  file_path,
)

df.tail()

X = df.drop(["Species","Id"],axis=1)
Y = df["Species"]

scaler = StandardScaler()
scaled_x = scaler.fit_transform(X)

X_train,X_test,Y_train,Y_test = train_test_split(scaled_x,Y)

from sklearn.neighbors import KNeighborsClassifier

for k in range(1, 11):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, Y_train)

    score = model.score(X_test, Y_test)
    print(f"K = {k}, Accuracy = {score:.2f}")

score = model.score(X_train,Y_train)
df.info()

predict = pd.DataFrame([{
    "SepalLengthCm": 6.7,
    "SepalWidthCm": 3.0,
    "PetalLengthCm": 5.2,
    "PetalWidthCm": 2.3
}])

predict_scaled = scaler.transform(predict)

result = model.predict(predict_scaled)
print(result)

from sklearn.metrics import accuracy_score

Y_pred = model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(Y_test, Y_pred)
print(cm)